POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: "tähän tulee token"

{
    "title": "moi",
    "author": "Kiva koulu3",
    "url":"jokuvaa",
    "likes": 4,
    "user": "5c00e9366aa5723668d26123"
}